name: Build and Package
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cpack_generator: [DEB, RPM, TGZ, ZIP]
          - os: windows-latest
            cpack_generator: [WIX, ZIP]
          - os: macos-latest
            cpack_generator: [DragNDrop, ZIP, TGZ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential rpm
      - name: Install CMake on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew update
          brew install cmake
      - name: Configure CMake
        run: cmake -S. -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package with CPack
        working-directory: ${{github.workspace}}/build
        run: |
          for gen in ${{ join(matrix.cpack_generator, ' ') }}; do
            cpack -G $gen
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-packages
          path: |
            build/*.deb
            build/*.rpm
            build/*.zip
            build/*.tar.gz
            build/*.msi
            build/*.dmg