name: BuildAndRelease

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-package:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y rpm

      - name: Configure build
        run: >
          cmake -S . -B build
          ${{ runner.os == 'Windows' && '-G "Visual Studio 17 2022" -A x64' || '-DCMAKE_BUILD_TYPE=Release' }}

      - name: Compile project
        run: cmake --build build --config Release

      - name: Install files for packaging
        run: cmake --install build --prefix build/out

      - name: Package binaries
        shell: bash
        run: |
          cd build
          if [ "${{ runner.os }}" == "Linux" ]; then
            cpack -G DEB
            cpack -G RPM
          elif [ "${{ runner.os }}" == "macOS" ]; then
            cpack -G DragNDrop
          else
            cpack -G WIX
          fi

      - name: Archive source code
        if: runner.os == 'Linux'
        run: |
          git archive --format=tar.gz -o source.tar.gz HEAD
          git archive --format=zip -o source.zip HEAD

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            build/*.deb
            build/*.rpm
            build/*.msi
            build/*.dmg
            build/*.zip
            build/*.tar.gz

  release:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: release-assets/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}