name: Build and Package
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            cpack_generator: "DEB;RPM;TGZ;ZIP"
          - os: windows-latest
            cpack_generator: "WIX"
          - os: macos-latest
            cpack_generator: "DragNDrop"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential rpm

      - name: Configure CMake
        run: cmake -S. -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Package with CPack
        working-directory: build
        run: cpack -G ${{ matrix.cpack_generator }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-packages
          path: build/*.{deb,rpm,zip,tar.gz,msi,dmg}